name: Build Documentation and Upload
# List of actions: https://github.com/marketplace?type=actions
# Build Documentation for master only and upload master only.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  builddoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install .[doc]
      - name: Build Documentation
        run: |
          cd docs && make html
  deploy:
    needs: builddoc
    if: github.event == 'push'
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './docs/build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

